In [ ]:
#列表中数据可以不同，从而浪费空间，但numpy数组只能有一个数据类型,有整数型和浮点型,具体类型谁多算谁
import numpy as np

In [ ]:
#两种类型转换
arr1 = np.array([1,2,3,4])#整数型
arr2 = np.array([1.0,2,3,4])#浮点型
print(arr1,arr2)
#整数变成浮点型
print(arr1.astype(float))
print(arr1/1)#与整数做除法
print(arr1*0.1)#与浮点数做计算都可以
#浮点型变成整数型
print(arr2.astype(int))

[1 2 3 4] [1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[0.1 0.2 0.3 0.4]
[1 2 3 4]


In [19]:
#多维数组
#数组的创建，ones函数是创建一个全是一的数组，n行m列，注意双层括号
arr1 = np.ones((2),dtype = int)#一维数组,后面是定义成整形，默认是浮点型
print(arr1)
arr2 = np.ones((1,2),dtype = int)#二维数组
print(arr2)
arr3 = np.ones((2,3),dtype = int)#三维
print(arr3)
print(arr3.shape)


[1 1]
[[1 1]]
[[1 1 1]
 [1 1 1]]
(2, 3)


In [23]:
#不同维度数组的转换reshape(n,m)目标是转换成n行m列，注意，当其他的参数确定，剩下的一个参数可以写成-1，让自己计算
#reshape函数
arr1 = np.arange(10)#创建一个0到9一维数组
arr2 = np.ones((1,2),dtype = int)
arr3 = np.ones((2,3),dtype = int)
arr4 = arr1.reshape(2,-1)#总个数是不变的
print(arr4,arr4.shape)
arr5=arr4.reshape(1,-1)
print(arr5,arr5.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)


In [ ]:
#注意以下都将一维数组称作向量，二维数组称作矩阵

In [34]:
#创建数组
#方法一：创建指定数组
arr1 = np.array([1,2])#1行，若是一列([1],[2])
print(arr1)
#方法二：创建递增数组
arr2 = np.arange(0,10,2)#开始结束索引，以及步长
print(arr2)
#方法三：创建全是相同元素的数组
arr3 = 3.0*np.ones((2,3),dtype = int)
print(arr3)
#创建随机数组np.random()，注意random函数默认是输出0到1的数字，如果想要输出n到m的要使用(m-n)*np.random.random((s,t))+n,注意s，t是形状
arr4 = np.random.random((2,5))#后面的2，5是形状
print(f"arr4={arr4}")
#60到100
arr5 = (100-60)*np.random.random((3,4))+60
arr5 = arr5.astype(int)#转换成整形
print(f"arr5={arr5}")
#服从正态分布的随机数组
arr6 = np.random.normal(0,1,(2,3))#均值方差和形状
print(f"arr6={arr6}")

[1 2]
[0 2 4 6 8]
[[3. 3. 3.]
 [3. 3. 3.]]
arr4=[[0.82433093 0.68876035 0.60110462 0.38300573 0.85841716]
 [0.49464014 0.65003856 0.51443114 0.29808388 0.38546301]]
arr5=[[91 83 78 65]
 [83 89 85 65]
 [92 85 62 61]]
arr6=[[ 0.17562267 -1.52585621  0.688888  ]
 [ 0.38786742 -2.63528196 -0.19143456]]


In [ ]:
#数组的索引
arr1 = np.arange(10)
print(arr1[-1])
arr2 = np.arange(10).reshape((2,-1))
print(arr2[-1,-1])
arr2[1,1] = 100#注意索引还是从0开始
print(arr2)

9
9
[[  0   1   2   3   4]
 [  5 100   7   8   9]]


In [ ]:
#花式索引
arr1 = np.arange(1,17).reshape(4,4)
print(arr1[[1,1],[2,2]])#意思是[[行，行]，[列，列]]对应位置两两组合成一个新向量
#也可以加一个等号多个同时换元素

[7 7]


In [ ]:
#数组切片
