In [ ]:
#列表中数据可以不同，从而浪费空间，但numpy数组只能有一个数据类型,有整数型和浮点型,具体类型谁多算谁
import numpy as np

In [ ]:
#两种类型转换
arr1 = np.array([1,2,3,4])#整数型
arr2 = np.array([1.0,2,3,4])#浮点型
print(arr1,arr2)
#整数变成浮点型
print(arr1.astype(float))
print(arr1/1)#与整数做除法
print(arr1*0.1)#与浮点数做计算都可以
#浮点型变成整数型
print(arr2.astype(int))

[1 2 3 4] [1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[0.1 0.2 0.3 0.4]
[1 2 3 4]


In [19]:
#多维数组
#数组的创建，ones函数是创建一个全是一的数组，n行m列，注意双层括号
arr1 = np.ones((2),dtype = int)#一维数组,后面是定义成整形，默认是浮点型
print(arr1)
arr2 = np.ones((1,2),dtype = int)#二维数组
print(arr2)
arr3 = np.ones((2,3),dtype = int)#三维
print(arr3)
print(arr3.shape)


[1 1]
[[1 1]]
[[1 1 1]
 [1 1 1]]
(2, 3)


In [23]:
#不同维度数组的转换reshape(n,m)目标是转换成n行m列，注意，当其他的参数确定，剩下的一个参数可以写成-1，让自己计算
#reshape函数
arr1 = np.arange(10)#创建一个0到9一维数组
arr2 = np.ones((1,2),dtype = int)
arr3 = np.ones((2,3),dtype = int)
arr4 = arr1.reshape(2,-1)#总个数是不变的
print(arr4,arr4.shape)
arr5=arr4.reshape(1,-1)
print(arr5,arr5.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)


In [ ]:
#注意以下都将一维数组称作向量，二维数组称作矩阵

In [34]:
#创建数组
#方法一：创建指定数组
arr1 = np.array([1,2])#1行，若是一列([1],[2])
print(arr1)
#方法二：创建递增数组
arr2 = np.arange(0,10,2)#开始结束索引，以及步长
print(arr2)
#方法三：创建全是相同元素的数组
arr3 = 3.0*np.ones((2,3),dtype = int)
print(arr3)
#创建随机数组np.random()，注意random函数默认是输出0到1的数字，如果想要输出n到m的要使用(m-n)*np.random.random((s,t))+n,注意s，t是形状
arr4 = np.random.random((2,5))#后面的2，5是形状
print(f"arr4={arr4}")
#60到100
arr5 = (100-60)*np.random.random((3,4))+60
arr5 = arr5.astype(int)#转换成整形
print(f"arr5={arr5}")
#服从正态分布的随机数组
arr6 = np.random.normal(0,1,(2,3))#均值方差和形状
print(f"arr6={arr6}")

[1 2]
[0 2 4 6 8]
[[3. 3. 3.]
 [3. 3. 3.]]
arr4=[[0.82433093 0.68876035 0.60110462 0.38300573 0.85841716]
 [0.49464014 0.65003856 0.51443114 0.29808388 0.38546301]]
arr5=[[91 83 78 65]
 [83 89 85 65]
 [92 85 62 61]]
arr6=[[ 0.17562267 -1.52585621  0.688888  ]
 [ 0.38786742 -2.63528196 -0.19143456]]


In [ ]:
#数组的索引
arr1 = np.arange(10)
print(arr1[-1])
arr2 = np.arange(10).reshape((2,-1))
print(arr2[-1,-1])
arr2[1,1] = 100#注意索引还是从0开始
print(arr2)

9
9
[[  0   1   2   3   4]
 [  5 100   7   8   9]]


In [ ]:
#花式索引
arr1 = np.arange(1,17).reshape(4,4)
print(arr1[[1,1],[2,2]])#意思是[[行，行]，[列，列]]对应位置两两组合成一个新向量
#也可以加一个等号多个同时换元素

[7 7]


In [47]:
#数组切片,与之前切片一样
arr1 = np.arange(10)
print(arr1)
print(arr1[1:4:2])#开始结束步长
#矩阵切片
arr2 = np.arange(1,17).reshape(4,4)
print(f"arr2={arr2}")
print(f"arr2_cut={arr2[1:3:1,1:3:1]}")#和上面一样，不过切片是先从行切，然后切列
#提取部分行
print(arr2[2,:])
#提取部分列
print(arr2[:,2])

[0 1 2 3 4 5 6 7 8 9]
[1 3]
arr2=[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr2_cut=[[ 6  7]
 [10 11]]
[ 9 10 11 12]
[ 3  7 11 15]


In [ ]:
#注意切片被设置为原数组的视图，也就是说改变切片原数组也变化
arr1 = np.arange(10)
cut = arr1[:4]
cut[2]=100
print(arr1)
#所以深度学习中常常使用arr[:]=代替arr=
#如果不想改的话，可以如下
copy = arr1[:3].copy()#这时候两者独立

[  0   1 100   3   4   5   6   7   8   9]


In [ ]:
#数组的转置,转置只能对数组使用，一维向量要转化成数组
arr1 = np.arange(10)
print(arr1)
arr2 = arr1.reshape(1,-1)
print(arr2)
print(arr2.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [55]:
#数组的翻转np.flipud()上下，np.fliplr()左右，向量只能上下翻转
arr1 = np.arange(1,17)
print(np.flipud(arr1))
print("以下是二维数组")
arr2 = arr1.reshape(4,4)
print(f"arr2={arr2}")
print(f"上下翻转={np.flipud(arr2)}")
print(f"左右翻转={np.fliplr(arr2)}")

[16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
以下是二维数组
arr2=[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
上下翻转=[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
左右翻转=[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
#数组的拼接
#向量的拼接
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])
arr3 = np.concatenate([arr1,arr2])
print(arr3)
#矩阵的拼接
arr3 = arr1.reshape(2,2)
arr4 = arr2.reshape(2,2)
print(np.concatenate([arr3,arr4]))#行拼接，默认是行
print(np.concatenate([arr3,arr4],axis=1))#列拼接

[1 2 3 4 4 5 6 7]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [3 4 6 7]]


In [61]:
#向量的分裂
arr1 = np.arange(10)
arr2,arr3,arr4=np.split(arr1,[2,7])
print(arr2,arr3,arr4)

[0 1] [2 3 4 5 6] [7 8 9]


In [66]:
#矩阵的分裂
arr = np.arange(1,9).reshape(2,-1)
print(arr,'\n')
arr1,arr2=np.split(arr,[1],axis = 0)#按照行分裂
arr3,arr4=np.split(arr,[2],axis =1)#按照列划分
print(arr1,'\n',arr2,'\n',arr3,'\n',arr4)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2 3 4]] 
 [[5 6 7 8]] 
 [[1 2]
 [5 6]] 
 [[3 4]
 [7 8]]


In [ ]:
#矩阵计算都是全部元素计算
arr = np.arange(1,9).reshape(2,-1)
print(arr+10)
#要注意：矩阵与矩阵之间是可以乘法*，也可以幂方**

[[11 12 13 14]
 [15 16 17 18]]


In [ ]:
#广播
#向量被广播
arr1 = np.array([100,0,100])
arr2 = np.random.random((5,3))
print(arr1*arr2)
#也就是说向量为了乘法自动复制自己行让自己适配矩阵

[[79.19410844  0.         93.31581554]
 [78.34556267  0.         27.7374397 ]
 [32.15126403  0.         45.81592006]
 [60.26575082  0.         73.70468125]
 [45.54021598  0.         69.61244908]]


In [71]:
#矩阵被广播
arr1 = np.array([100,0,100]).reshape(3,1)
arr2 = np.random.random((3,5))
print(arr1*arr2)

[[44.16289254 81.27601483 83.13994185 57.99347022 58.56166742]
 [ 0.          0.          0.          0.          0.        ]
 [71.97653437 46.79945901  8.54421596 51.52636846  5.90230764]]


In [ ]:
#矩阵乘积
#这是按照线性代数的矩阵乘法计算，上面的都是元素对应乘法
arr1 = np.arange(5)
arr2 = np.arange(5)#.reshape(5,1)
print(np.dot(arr1,arr2))
#这是向量内积，如果把reshape不注释的话就是矩阵乘法

30


In [74]:
#数学函数
arr1 = np.array([-1,0,1])
#1、绝对值函数
print(f"绝对值={np.abs(arr1)}")
#2、三角函数sin为例
print(f"sin={np.sin(arr1)}")
#3、指数函数
print(f"e^x={np.exp(arr1)}")
#4\对数函数
print(f"ln(x)={np.log(arr1)}")
print(f"log2(x)={np.log(arr1)/np.log(2)}")#换底公式


绝对值=[1 0 1]
sin=[-0.84147098  0.          0.84147098]
e^x=[0.36787944 1.         2.71828183]
ln(x)=[ nan -inf   0.]
log2(x)=[ nan -inf   0.]


C:\Users\get\AppData\Local\Temp\ipykernel_34876\1985688477.py:10: RuntimeWarning: divide by zero encountered in log
  print(f"ln(x)={np.log(arr1)}")
C:\Users\get\AppData\Local\Temp\ipykernel_34876\1985688477.py:10: RuntimeWarning: invalid value encountered in log
  print(f"ln(x)={np.log(arr1)}")
C:\Users\get\AppData\Local\Temp\ipykernel_34876\1985688477.py:11: RuntimeWarning: divide by zero encountered in log
  print(f"log2(x)={np.log(arr1)/np.log(2)}")#换底公式
C:\Users\get\AppData\Local\Temp\ipykernel_34876\1985688477.py:11: RuntimeWarning: invalid value encountered in log
  print(f"log2(x)={np.log(arr1)/np.log(2)}")#换底公式


In [ ]:
#聚合函数，注意axis=0的时候是一列一列的算，axis=1的时候是一行一行算
#最值函数：np.max(arr,axis=1)
#求和函数：np.sum(arr,axis=1)
#均值函数：np.mean(arr,axis=1)
#标准差函数：np.std(arr,axis=1)
#不带axis的时候就是整体算
#如果有缺失值的话，使用np.nan(上面函数)(arr,axis=1)
#np.any()函数
#np.all()函数

In [ ]:
#布尔型数组
#创建
arr1 = np.arange(1,9)
print((arr1>=5 )| (arr1<3))#或 

[ True  True False False  True  True  True  True]


In [ ]:
'''
np=troch
array=tensor张量
n维数组=n阶张量
arr->ts张量：te = torch.tensor(arr)
ts->arr:arr = np.array(ts)
'''

'\nnp=troch\narray=tensor张量\nn维数组=n阶张量\n'